server:
  port: 8888
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    bootstrap-servers: localhost:9092
kafka:
  bootstrapAddress: localhost:9092