spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      client-id: 1
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
  data:
    mongodb:
      host: ${DB_MONGO_HOST}
      port: ${DB_MONGO_PORT}
      database: ${DB_MONGO_DATABASE}
      auto-index-creation: true
      authentication-database: admin
      username: root
      password: secret
kafka:
  bootstrapAddress: ${KAFKA_BOOTSTRAP_SERVER}
  topic:
    name: "kafka_topic"
    group_id: "group_id"